run:
	qmk new-keymap -kb keychron/k8_pro/ansi/rgb -km autostart
	qmk compile -kb keychron/k8_pro/ansi/rgb -km autostart
	qmk flash -kb keychron/k8_pro/ansi/rgb -km autostart

flash-via:
	qmk flash firmware/K8-Pro-ANSI-RGB-v1.02.bin