services:
  keychron-launcher:
    build: .
    container_name: keychron-launcher
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Optional: Mount a directory for Caddy data persistence
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "com.docker.description=Keychron Launcher Website with Custom Firmware"

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local 